version: "3.8"

services:
  mysql:
    image: mysql:8
    container_name: myshop-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'Enter your password'
      MYSQL_DATABASE: myshop
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - myshop-net
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-pGograj@2211"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  backend:
    image: gograj/shipsy-backend:latest   # <-- from Docker Hub
    container_name: myshop-backend
    restart: on-failure
    ports:
      - "3000:3000"
    env_file:
      - ./backend.env                     # create small file with your env vars
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - myshop-net

  frontend:
    image: gograj/shipsy-frontend:latest  # <-- from Docker Hub
    container_name: myshop-frontend
    ports:
      - "5173:5173"
    env_file:
      - ./frontend.env                    # simple env file for frontend vars
    depends_on:
      - backend
    networks:
      - myshop-net

volumes:
  mysql-data:

networks:
  myshop-net:
    driver: bridge
